server:
  port: 8884

spring:
  application:
    name: sc-zipkin
  rabbitmq:
    host: 192.168.235.32
    username: admin
    password: 123456
    port: 5672

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}
