version: '2'
services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - 15672:15672
  sc-registry:
    image: spring-cloud-docker/sc-registry
    ports:
      - "8881:8881"
  sc-config:
    image: spring-cloud-docker/sc-config
    ports:
      - "8882:8882"
  sc-monitor:
    image: spring-cloud-docker/sc-monitor
    ports:
      - "8883:8883"
  sc-zipkin:
    image: spring-cloud-docker/sc-zipkin
    ports:
      - "8884:8884"
  sc-gateway:
    image: spring-cloud-docker/sc-gateway
    ports:
      - "8081:8081"
  sc-auth:
    image: spring-cloud-docker/sc-auth
    ports:
      - "8082:8082"
  sc-servicea:
    image: spring-cloud-docker/sc-servicea
  sc-serviceb:
    image: spring-cloud-docker/sc-serviceb