server:
  port: 8888

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    metadata-map:
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@127.0.0.1:8761/eureka/

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeikerxiao/SpringCloudDocker
          search-paths: config-repo
  rabbitmq:
    host: 192.168.235.32
    username: admin
    password: 123456
    port: 5672


security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
